name: Build AppImage with linuxdeployqt

on:
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/csreviser/qt6-static:6.9.0-ubuntu22.04
      options: --privileged

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git checkout feature
          git submodule update --init --recursive
          cp ./qss_files/stylesheet-ubu.qss ./

      - name: Build Application
        run: |
          cd CaptureStream2
          mkdir -p build
          cd build
          /opt/qt6-static/bin/qmake ../CaptureStream2.pro
          make -j$(nproc)

      - name: Download linuxdeployqt
        run: |
          cd CaptureStream2
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O linuxdeployqt.AppImage
          chmod +x linuxdeployqt.AppImage

      - name: Set QMAKE path
        run: echo "QMAKE=/opt/qt6-static/bin/qmake" >> $GITHUB_ENV

      - name: Prepare AppDir
        run: |
          cd CaptureStream2
          mkdir -p AppDir/usr/bin
          cp build/CaptureStream2 AppDir/usr/bin/
          cp icon.png AppDir/
          cp CaptureStream2.desktop AppDir/

      - name: Run linuxdeployqt
        run: |
          cd CaptureStream2
          ./linuxdeployqt.AppImage AppDir/usr/share/applications/CaptureStream2.desktop \
            -appimage -bundle-non-qt-libs

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: CaptureStream2.AppImage
          path: ./CaptureStream2*.AppImage
