name: Build Qt 6.9 Static and Upload to Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgl1-mesa-dev \
            libxcb-render-util0-dev \
            libxcb-xinput-dev \
            libxcb-xfixes0-dev \
            ninja-build \
            python3 \
            perl \
            cmake \
            curl \
            git \
            wget \
            libglib2.0-dev \
            libdbus-1-dev \
            libfontconfig1-dev \
            libfreetype-dev \
            libgtk-3-dev \
            libxcb-shm0-dev \
            libxcb-cursor-dev \
            libxcb-xinput-dev \
            libxcb-shm0-dev \
            libx11-dev libx11-xcb-dev libxcb1-dev libxcb-util-dev \
            libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev \
            libxcb-render-util0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev \
            libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxrender-dev \
            libxkbcommon-dev libxkbcommon-x11-dev libxcb-ewmh-dev \
            libxext-dev libxfixes-dev libxrandr-dev ibxi-dev libxcomposite-dev \
            libxcursor-dev libxdamage-dev libxtst-dev ibxss-dev ibxv-dev libglu1-mesa-dev \
            libxcb-util0-dev libgbm-dev libxcb-dri3-dev libxcb-present-dev libxcb-glx0-dev \
            libssl-dev \
            libwayland-dev \
            libwayland-egl-backend-dev

      - name: Download Qt 6.9 source
        run: |
          curl -LO https://download.qt.io/official_releases/qt/6.9/6.9.0/single/qt-everywhere-src-6.9.0.tar.xz
          tar xf qt-everywhere-src-6.9.0.tar.xz

      - name: Configure and build Qt statically (make version)
        run: |
          mkdir qt-build
          cd  qt-build
          ../qt-everywhere-src-6.9.0/configure \
            -top-level \
            -prefix ../qt-build/qt6-static-install \
            -static -static-runtime -release \
            -opensource -confirm-license \
            -nomake examples -nomake tests \
            -skip qt3d -skip qtactiveqt -skip qtcharts -skip qtconnectivity \
            -skip qtdatavis3d -skip qtdoc -skip qtgamepad -skip qtgraphicaleffects \
            -skip qtimageformats -skip qtlocation -skip qtmacextras -skip qtnetworkauth \
            -skip qtquickcontrols2 -skip qtremoteobjects -skip qtscxml \
            -skip qtsensors -skip qtserialbus -skip qtserialport -skip qtspeech \
            -skip qtsvg -skip qttools -skip qttranslations -skip qtvirtualkeyboard \
            -skip qtwayland -skip qtwebchannel -skip qtwebengine -skip qtwebsockets \
            -skip qtwebview -skip qtwinextras -skip qtlottie -skip qtmultimedia \
            -skip qtshadertools -skip qtpositioning -skip qtquicktimeline \
            -skip qtquick3d \
            -skip qtgraphs \
            -skip qtquick3dphysics \
            -skip qttools \
            -skip qtquickeffectmaker \
            -no-pch \
            -qt-harfbuzz \
            -qt-freetype \
            -qt-libpng \
            -qt-zlib \
            -qt-libjpeg \
            -qt-pcre \
            -icu \
            -qt-doubleconversion \
            -dbus \
            -platform linux-g++ \
            -feature-xcb \
            -c++std c++20 

          cmake --build . --parallel
          cmake --install .

#            -platform linux-g++ \
#            -c++std c++20 \
#            -skip qtimageformats -skip qtwebengine \
#            -skip qt3d -skip qt5compat -skip qtactiveqt -skip qtcharts -skip qtcoap -skip qtconnectivity \
#            -skip qtdatavis3d -skip qtdoc -skip qtlottie -skip qtmqtt -skip qtnetworkauth -skip qtopcua \
#            -skip qtserialport -skip qtpositioning -skip qtquicktimeline -skip qtquick3d -skip qtremoteobjects \
#            -skip qtscxml -skip qtsensors -skip qtserialbus -skip qtvirtualkeyboard \
#            -skip qtwebchannel -skip qtwebengine -skip qtwebview -skip qtquick3dphysics -skip qtspeech -skip qtlocation \
#            -skip qthttpserver

      - name: Package Qt
        run: |
          cd qt-build
          tar -czf qt6.9.0-linux-static.tar.gz qt6-static-install

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt6.9.0-static-ubuntu22
          name: Qt 6.9.0 Static ubuntu22.04
          files: qt-build/qt6.9.0-linux-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
