name: Check Qt6 Static Libraries in Build Dir

on:
  workflow_dispatch:

jobs:
  check-static-libs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/csreviser/qt6-win-arm:latest

    steps:
      - name: Look for .a files in qtbase build output
        run: |
          echo "Searching for .a files under /qtbase"
          found=$(find /build/qt6/qtbase -type f -name "*.a")
          if [ -n "$found" ]; then
            echo "✅ .a static libraries found:"
            echo "$found"
          else
            echo "❌ No .a static libraries found in /qtbase"
            echo "Static build may have failed or is not complete."
            exit 1
          fi

      - name: Check for static .a files in Qt install prefix
        run: |
          echo "Checking for .a files in $QT6_ARM_PREFIX/lib"
          if compgen -G "$QT6_ARM_PREFIX/lib/*.a" > /dev/null; then
            echo "✅ .a static libraries found:"
            ls -lh "$QT6_ARM_PREFIX/lib/"*.a
          else
            echo "❌ No .a static libraries found in $QT6_ARM_PREFIX/lib"
            echo "Check if static build succeeded and install step copied .a files."
            exit 1
          fi