name: 2-5. Build CaptureStream2 for Windows ARM

on:
  workflow_dispatch:
    inputs:
      yyyymmdd:
        description: 'Date string for release (yyyymmdd)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/csreviser/qt6-win-arm:latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git checkout feature
          git submodule update --init --recursive

      - name: Create build directory
        run: |
          mkdir -p build

      - name: Configure with CMake
        working-directory: CaptureStream2
        run: >
          /usr/local/Qt-6.9.0/bin/qt-cmake
            -S .
            -B ../build 
            -G Ninja 
            -DCMAKE_BUILD_TYPE=Release 
            -DCMAKE_SYSTEM_NAME=Windows 
            -DCMAKE_SYSTEM_PROCESSOR=ARM64 
            -DCMAKE_TOOLCHAIN_FILE=/opt/llvm-mingw/toolchain.cmake
            -DCMAKE_PREFIX_PATH="/opt/qt6" 
            -DQT_HOST_PATH="/opt/qt6-host"

      - name: Build
        run: cmake --build build --parallel

      - name: Create WinCaptureStream2 directory and move exe
        shell: bash
        run: |
          mkdir -p build/WinCaptureStream2
          mv build/CaptureStream2.exe build/WinCaptureStream2/
          cp ./CaptureStream2/qss_files/stylesheet-win.qss build/WinCaptureStream2/

      - name: Create ZIP file
        run: |
          cd build
          zip -r "CaptureStream-arm64-${{ github.event.inputs.yyyymmdd }}.zip" WinCaptureStream2

      - name: Format release title
        id: format_date
        shell: bash
        run: |
          yyyy="${{ github.event.inputs.yyyymmdd }}"
          echo "title=${yyyy:0:4}/${yyyy:4:2}/${yyyy:6:2}版リリース (Windows ARM)" >> "$GITHUB_OUTPUT"

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/CaptureStream-arm64-${{ github.event.inputs.yyyymmdd }}.zip
          tag_name: ${{ github.event.inputs.yyyymmdd }}
          name: ${{ steps.format_date.outputs.title }}
          body: "Static build for Windows ARM (Qt 6.9.0)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
