name: 2-2. Win Qt6 32bit Static Build (MXE)

on:
  workflow_dispatch:
    inputs:
      yyyymmdd:
        description: 'Date string for release (yyyymmdd)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/csreviser/qt6-mxe-x86-static:6.9.0

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git checkout feature
          git submodule update --init --recursive

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: >
          /opt/mxe/usr/x86_64-w64-mingw32.static/qt6/bin/qt-cmake
          -S CaptureStream2
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH="/opt/mxe/usr/x86_64-w64-mingw32.static/qt6/bin"
          -DCMAKE_FIND_ROOT_PATH="/opt/mxe/usr/x86_64-w64-mingw32.static"
          -DCMAKE_SYSTEM_NAME=Windows
          -DCMAKE_INSTALL_PREFIX=install
          -DQT_HOST_PATH="/opt/mxe/usr/x86_64-w64-mingw32.static/qt6"

      - name: Build
        run: cmake --build build --parallel

      - name: Create WinCaptureStream2 directory and move exe
        shell: bash
        run: |
          mkdir -p build/WinCaptureStream2
          mv build/CaptureStream2.exe build/WinCaptureStream2/
          cp ./CaptureStream2/qss_files/stylesheet-win.qss build/WinCaptureStream2/

      - name: Create ZIP file
        run: |
          cd build
          zip -r "CaptureStream-Windows-x86-${{ github.event.inputs.yyyymmdd }}.zip" WinCaptureStream2

      - name: Format release title
        id: format_date
        shell: bash
        run: |
          yyyy="${{ github.event.inputs.yyyymmdd }}"
          echo "title=${yyyy:0:4}/${yyyy:4:2}/${yyyy:6:2}版リリース" >> "$GITHUB_OUTPUT"

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/CaptureStream-x86-${{ github.event.inputs.yyyymmdd }}.zip
          tag_name: ${{ github.event.inputs.yyyymmdd }}
          name: ${{ steps.format_date.outputs.title }}
          body: "Static build for Windows (Qt 6.9.0, MXE)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
