name: 2. Build CaptureStream2 with MXE

on:
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mxe-builder repository
        uses: actions/checkout@v4


    - name: Clone CaptureStream2
      run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git checkout feature
          git submodule update --init --recursive

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Download MXE artifact from Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download  mxe-qt6-v1 \
            --repo ${{ github.repository }} \
            --pattern "mxe-qt6-x86_64.tar.gz"

      - name: Extract MXE environment
        run: |
          mkdir mxe
          tar -xzf mxe-qt6-x86_64.tar.gz -C ./mxe --strip-components=1

      - name: Build CaptureStream2 with MXE
        run: |
          export PATH=$(pwd)/mxe/usr/bin:$PATH
          cd CaptureStream2
          mkdir build
          cd build
          x86_64-w64-mingw32.static-cmake ..
          make -j$(nproc)

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: capturestream2-windows
          path: CaptureStream2/build/*.exe
