name: 3-2. arn Build CS2 ubuntu22 with Qt Static (Docker)

on:
  workflow_dispatch:
    inputs:
      yyyymmdd:
        description: 'Date string for release (yyyymmdd)'
        required: true

env:
  QT_VERSION: 6.9.0
#  IMAGE_NAME: ghcr.io/csreviser/qt6-static:6.9.0-ubuntu22.04
# ghcr.io/csreviser/qt6-ubuntu-static:latest

jobs:
  build:
    runs-on: ubuntu-arm
    container:
      image: ghcr.io/csreviser/qt6-static-arn:latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          apt-get update
          apt-get install -y curl zip
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
          gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
          tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt-get update
          apt-get install -y gh p7zip-full lzip bzip2
          
      - name: Mark repo as safe
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git checkout feature
          git submodule update --init --recursive

      - name: Build using Docker container with Qt static
        run: |
          cd CaptureStream2
          mkdir -p build && cd build
          qt-cmake .. -DQT_DEBUG_FIND_PACKAGE=ON
          cmake --build . --parallel
          mkdir -p LinCaptureStream2
          mv CaptureStream2 ./LinCaptureStream2/
          cp ../qss_files/stylesheet-ubu.qss ./LinCaptureStream2
          cp -r ../qss_files/License ./LinCaptureStream2
          wget -qO ffmpeg-static-ubuntu-arm.zip https://github.com/CSReviser/ffmpeg-build/releases/download/7.1.1/ffmpeg-static-ubuntu-arm.zip
          7z e ffmpeg-static-ubuntu-arm.zip ffmpeg -o./LinCaptureStream2
          chmod -R 755 ./LinCaptureStream2

      - name: Create ZIP file
        run: |
          cd CaptureStream2/build
          zip -r "CaptureStream2-ubuntu-arn-${{ github.event.inputs.yyyymmdd }}.zip" LinCaptureStream2
      
      - name: Upload zip to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: CaptureStream2/build/CaptureStream2-ubuntu-arn-${{ github.event.inputs.yyyymmdd }}.zip
          tag_name: ${{ needs.mac_build.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
