name: 0. test

on:
  workflow_dispatch:


env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  QT_VERSION: 6.12.0

jobs:

  setup:
    runs-on: ubuntu-latest
    # ジョブ単位で定義する場合はここに env: QT_VERSION: 6.12.0 でも可
    outputs:
      qt_version: ${{ env.QT_VERSION }}
    steps:
      - run: echo "QT_VERSION=${{ env.QT_VERSION }}"  # ジョブには最低1ステップ必要


  win_build:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/csreviser/qt6-mxe-static-path:${{ needs.setup.outputs.qt_version }}
 #     image: ghcr.io/csreviser/qt6-mxe-static-path:6.12.0
#      image: "ghcr.io/${USER}/qt6-mxe-static-path:${QT_VERSION}"
#      image: ghcr.io/csreviser/qt6-mxe-static:6.12.0
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v6

      - name: Mark repo as safe
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git checkout feature
          git submodule update --init --recursive

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: >
          /opt/mxe/usr/x86_64-w64-mingw32.static/qt6/bin/qt-cmake
          -S CaptureStream2
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH="/opt/mxe/usr/x86_64-w64-mingw32.static/qt6/bin"
          -DCMAKE_FIND_ROOT_PATH="/opt/mxe/usr/x86_64-w64-mingw32.static"
          -DCMAKE_SYSTEM_NAME=Windows
          -DCMAKE_INSTALL_PREFIX=install
          -DQT_HOST_PATH="/opt/mxe/usr/x86_64-w64-mingw32.static/qt6"

      - name: Build
        run: cmake --build build --parallel

      - name: Create WinCaptureStream2 directory and move exe
        shell: bash
        run: |
          mkdir -p build/WinCaptureStream2
          mv build/CaptureStream2.exe build/WinCaptureStream2/
          cp ./CaptureStream2/qss_files/stylesheet-win.qss build/WinCaptureStream2/
          cp -r ./CaptureStream2/qss_files/License build/WinCaptureStream2/
          mkdir -p build/stylesheet-win
          cp -r ./CaptureStream2/qss_files/stylesheet-win build/
          cp -r ./CaptureStream2/qss_files/stylesheet-mac build/
          wget -qO ffmpeg.zip https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-9.0.2-windows-x64-static.zip
          7z e ffmpeg.zip ffmpeg.exe -o./build/WinCaptureStream2/
 #         cp /opt/mxe/usr/x86_64-w64-mingw32.static/bin/ffmpeg.exe build/WinCaptureStream2/
          
      - name: Install GitHub CLI
        run: |
          apt-get update
          apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
          gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
          tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt-get update
          apt-get install -y gh

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: CaptureStream2-x64
          path: build/


      - name: Inspect build environment
        run: |
          echo "=== GCC ==="
          /opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc --version

          echo "=== G++ ==="
          /opt/mxe/usr/bin/x86_64-w64-mingw32.static-g++ --version

          echo "=== CMake ==="
          cmake --version

          echo "=== Qt ==="
          /opt/mxe/usr/x86_64-w64-mingw32.static/qt6/bin/qmake --version

      - name: Inspect executable
        run: |
          file build/WinCaptureStream2/CaptureStream2.exe
          objdump -f build/WinCaptureStream2/CaptureStream2.exe
          objdump --section-headers build/WinCaptureStream2/CaptureStream2.exe | grep -E 'debug|text'
          objdump -x build/WinCaptureStream2/CaptureStream2.exe > build/CaptureStream2-objdump.txt

  win_build-qt611:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/csreviser/qt6-mxe-static:6.11.2

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v6

      - name: Mark repo as safe
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git checkout feature
          git submodule update --init --recursive

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: >
          /opt/mxe/usr/x86_64-w64-mingw32.static/qt6/bin/qt-cmake
          -S CaptureStream2
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH="/opt/mxe/usr/x86_64-w64-mingw32.static/qt6/bin"
          -DCMAKE_FIND_ROOT_PATH="/opt/mxe/usr/x86_64-w64-mingw32.static"
          -DCMAKE_SYSTEM_NAME=Windows
          -DCMAKE_INSTALL_PREFIX=install
          -DQT_HOST_PATH="/opt/mxe/usr/x86_64-w64-mingw32.static/qt6"

      - name: Build
        run: cmake --build build --parallel

      - name: Create WinCaptureStream2 directory and move exe
        shell: bash
        run: |
          mkdir -p build/WinCaptureStream2
          mv build/CaptureStream2.exe build/WinCaptureStream2/
          cp ./CaptureStream2/qss_files/stylesheet-win.qss build/WinCaptureStream2/
          cp -r ./CaptureStream2/qss_files/License build/WinCaptureStream2/
          mkdir -p build/stylesheet-win
          cp -r ./CaptureStream2/qss_files/stylesheet-win build/
          cp -r ./CaptureStream2/qss_files/stylesheet-mac build/
          wget -qO ffmpeg.zip https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-9.0.2-windows-x64-static.zip
          7z e ffmpeg.zip ffmpeg.exe -o./build/WinCaptureStream2/
 #         cp /opt/mxe/usr/x86_64-w64-mingw32.static/bin/ffmpeg.exe build/WinCaptureStream2/
          
      - name: Install GitHub CLI
        run: |
          apt-get update
          apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
          gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
          tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt-get update
          apt-get install -y gh

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: CaptureStream2-x64-Qt611
          path: build/

      - name: Inspect build environment
        run: |
          echo "=== GCC ==="
          /opt/mxe/usr/bin/x86_64-w64-mingw32.static-gcc --version

          echo "=== G++ ==="
          /opt/mxe/usr/bin/x86_64-w64-mingw32.static-g++ --version

          echo "=== CMake ==="
          cmake --version

          echo "=== Qt ==="
          /opt/mxe/usr/x86_64-w64-mingw32.static/qt6/bin/qmake --version

      - name: Inspect executable
        run: |
          file build/WinCaptureStream2/CaptureStream2.exe
          objdump -f build/WinCaptureStream2/CaptureStream2.exe
          objdump --section-headers build/WinCaptureStream2/CaptureStream2.exe | grep -E 'debug|text'
          objdump -x build/WinCaptureStream2/CaptureStream2.exe > build/CaptureStream2-objdump.txt

  win32_build:
    needs: setup
    runs-on: ubuntu-latest
    container:
       image: ghcr.io/csreviser/qt6-mxe-static-path:${{ needs.setup.outputs.qt_version }}-32
#       image: ghcr.io/csreviser/qt6-mxe-static-path:6.12.0-32
#      image: "ghcr.io/${USER}/qt6-mxe-static-path:${QT_VERSION}-32"
#      image: ghcr.io/csreviser/qt6-mxe-x86-static:6.12.0

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v6

      - name: Mark repo as safe
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Install GitHub CLI
        run: |
          apt-get update
          apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
          gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
          tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt-get update
          apt-get install -y gh

      - name: Clone CaptureStream2
        run: |
          git clone https://github.com/CSReviser/CaptureStream2.git
          cd CaptureStream2
          git checkout feature
          git submodule update --init --recursive

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: >
          /opt/mxe/usr/i686-w64-mingw32.static/qt6/bin/qt-cmake
          -S CaptureStream2
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH="/opt/mxe/usr/i686-w64-mingw32.static/qt6/bin"
          -DCMAKE_FIND_ROOT_PATH="/opt/mxe/usr/i686-w64-mingw32.static"
          -DCMAKE_SYSTEM_NAME=Windows
          -DCMAKE_INSTALL_PREFIX=install
          -DQT_HOST_PATH="/opt/mxe/usr/i686-w64-mingw32.static/qt6"

      - name: Build
        run: cmake --build build --parallel

      - name: Create WinCaptureStream2 directory and move exe
        shell: bash
        run: |
          mkdir -p build/WinCaptureStream2
          mv build/CaptureStream2.exe build/WinCaptureStream2/
          cp ./CaptureStream2/qss_files/stylesheet-win.qss build/WinCaptureStream2/
          cp -r ./CaptureStream2/qss_files/License build/WinCaptureStream2/
          wget -qO ffmpeg.zip https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-9.0.2-windows-x86-static.zip
          7z e ffmpeg.zip ffmpeg.exe -o./build/WinCaptureStream2/
#          cp /opt/mxe/usr/i686-w64-mingw32.static/bin/ffmpeg.exe build/WinCaptureStream2/

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: CaptureStream2-x86
          path: build/WinCaptureStream2/

      - name: Inspect build environment
        run: |
          echo "=== GCC ==="
          /opt/mxe/usr/bin/i686-w64-mingw32.static-gcc --version

          echo "=== G++ ==="
          /opt/mxe/usr/bin//i686-w64-mingw32.static-g++ --version

          echo "=== CMake ==="
          cmake --version

          echo "=== Qt ==="
          /opt/mxe/usr/i686-w64-mingw32.static/qt6/bin/qmake --version

      - name: Inspect executable
        run: |
          file build/WinCaptureStream2/CaptureStream2.exe
          objdump -f build/WinCaptureStream2/CaptureStream2.exe
          objdump --section-headers build/WinCaptureStream2/CaptureStream2.exe | grep -E 'debug|text'
          objdump -x build/WinCaptureStream2/CaptureStream2.exe > build/CaptureStream2-objdump.txt

